version: '3.4'

services:
  verticalslice:
    image: ${DOCKER_REGISTRY-}verticalslice
    build:
      context: .
      dockerfile: VerticalSlice/Dockerfile
  mssql:
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
        - ACCEPT_EULA=1
        - MSSQL_USER=SA
        - MSSQL_SA_PASSWORD=P@sSw0rd!
        - MSSQL_PID=Developer
    ports:
        - "1433:1433"  
